server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/pessoas
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  redis:
    host: localhost
    port: 6379

cache:
  endereco:
    ttl-seconds: 86400   # 24h

feign:
  client:
    config:
      viacep:
        connectTimeout: 4000
        readTimeout: 4000